syntax = "proto3";

package inventory.v1;

import "google/protobuf/timestamp.proto";
// import "google/protobuf/wrappers.proto";

option go_package = "github.com/ArchibaldKronin/microservices_test/shared/pkg/proto/inventory/v1;inventory_v1";

// API для доступа к запчастям
service PartService {
  // Получить запчасть
  rpc GetPart(GetPartRequest) returns (GetPartResponse);

  // Получить запчасти по фильтру
  rpc ListPart(ListPartRequest) returns (ListPartResponse);
}

// Категория запчасти
enum Category {
  // стандартная
  CATEGORY_UNSPECIFIED = 0;
  // двигатель
  CATEGORY_ENGINE = 1;
  // топливо
  CATEGORY_FUEL = 2;
  // портхоул (??)
  CATEGORY_PORTHOLE = 3;
  // крыло
  CATEGORY_WING = 4;
}

// Размеры и вес
message Dimensions {
  // длина
  double length = 1;
  // ширина
  double width = 2;
  // высота
  double height = 3;
  // вес
  double weight = 4;
}

// Производитель
message Manufacturer {
  // Название производителя
  string name = 1;
  // Страна производства
  string country = 2;
  // Сайт производителя
  string website = 3;
}

// Метаданные
message Value {
  oneof value {
    string string_value = 1;
    int64 int64_value = 2;
    double double_value = 3;
    bool bool_value = 4;
  }
}

// Запчасть
message Part {
  string uuid = 1;
  string name = 2;
  string description = 3;
  double price = 4;
  int64 stock_quantity = 5;
  Category category = 6;
  Dimensions dimensions = 7;
  Manufacturer manufacturer = 8;
  repeated string tags = 9;
  map<string, Value> metadata = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 12;
}

// GetPartRequest Запрос на получение запчасти
message GetPartRequest {
  string uuid = 1;
}

// GetPartResponse Ответ с данными о запчасти
message GetPartResponse {
  Part part = 1;
}

// ListPartRequest Запрос получения запчастей по фильтру
message ListPartRequest {
  repeated string uuids = 1;
  repeated string names = 2;
  repeated Category categorys = 3;
  repeated string countrys = 4;
  repeated string tags = 5;
}

// ListPartResponse Ответ со списком всех запчастей по фильтру
message ListPartResponse {
  repeated Part parts = 1;
}
