{
 "title": "Microservices",
 "time": { "from": "2026-05-21T02:21:29.859Z", "to": "2026-05-21T14:21:29.859Z" },
 "panels": [
  {
   "title": "Orders revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "orders_revenue_total{job=\"order-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders create total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "orders_create_total{job=\"order-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assembly duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.9,\n  rate(assembly_duration_seconds_bucket[20m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "assembly_duration_seconds_bucket{job=\"assembly-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}