// Code generated for spaceship factory tests
// Archibald 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// OrderHTTPConfigConfig is an autogenerated mock type for the OrderHTTPConfigConfig type
type OrderHTTPConfigConfig struct {
	mock.Mock
}

type OrderHTTPConfigConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderHTTPConfigConfig) EXPECT() *OrderHTTPConfigConfig_Expecter {
	return &OrderHTTPConfigConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *OrderHTTPConfigConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderHTTPConfigConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type OrderHTTPConfigConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *OrderHTTPConfigConfig_Expecter) Address() *OrderHTTPConfigConfig_Address_Call {
	return &OrderHTTPConfigConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *OrderHTTPConfigConfig_Address_Call) Run(run func()) *OrderHTTPConfigConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHTTPConfigConfig_Address_Call) Return(_a0 string) *OrderHTTPConfigConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHTTPConfigConfig_Address_Call) RunAndReturn(run func() string) *OrderHTTPConfigConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function with no fields
func (_m *OrderHTTPConfigConfig) Port() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderHTTPConfigConfig_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type OrderHTTPConfigConfig_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *OrderHTTPConfigConfig_Expecter) Port() *OrderHTTPConfigConfig_Port_Call {
	return &OrderHTTPConfigConfig_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *OrderHTTPConfigConfig_Port_Call) Run(run func()) *OrderHTTPConfigConfig_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHTTPConfigConfig_Port_Call) Return(_a0 string) *OrderHTTPConfigConfig_Port_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHTTPConfigConfig_Port_Call) RunAndReturn(run func() string) *OrderHTTPConfigConfig_Port_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTime provides a mock function with no fields
func (_m *OrderHTTPConfigConfig) ReadTime() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadTime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// OrderHTTPConfigConfig_ReadTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTime'
type OrderHTTPConfigConfig_ReadTime_Call struct {
	*mock.Call
}

// ReadTime is a helper method to define mock.On call
func (_e *OrderHTTPConfigConfig_Expecter) ReadTime() *OrderHTTPConfigConfig_ReadTime_Call {
	return &OrderHTTPConfigConfig_ReadTime_Call{Call: _e.mock.On("ReadTime")}
}

func (_c *OrderHTTPConfigConfig_ReadTime_Call) Run(run func()) *OrderHTTPConfigConfig_ReadTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHTTPConfigConfig_ReadTime_Call) Return(_a0 time.Duration) *OrderHTTPConfigConfig_ReadTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHTTPConfigConfig_ReadTime_Call) RunAndReturn(run func() time.Duration) *OrderHTTPConfigConfig_ReadTime_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderHTTPConfigConfig creates a new instance of OrderHTTPConfigConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderHTTPConfigConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderHTTPConfigConfig {
	mock := &OrderHTTPConfigConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
