services:
  notification-service:
    build:
      context: ../../..
      dockerfile: deploy/docker/notification/Dockerfile

    container_name: notification-service

    env_file:
      - .env

    environment:
      - KAFKA_BROKERS=kafka:9092

    restart: unless-stopped

    networks:
      - microservices-net

networks:
  microservices-net:
    external: true