// Code generated for spaceship factory tests
// Archibald 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/ArchibaldKronin/microservices_test/order/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// TxManager is an autogenerated mock type for the TxManager type
type TxManager struct {
	mock.Mock
}

type TxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TxManager) EXPECT() *TxManager_Expecter {
	return &TxManager_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *TxManager) WithTransaction(ctx context.Context, fn func(repository.OrderRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(repository.OrderRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxManager_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type TxManager_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(repository.OrderRepository) error
func (_e *TxManager_Expecter) WithTransaction(ctx interface{}, fn interface{}) *TxManager_WithTransaction_Call {
	return &TxManager_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *TxManager_WithTransaction_Call) Run(run func(ctx context.Context, fn func(repository.OrderRepository) error)) *TxManager_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(repository.OrderRepository) error))
	})
	return _c
}

func (_c *TxManager_WithTransaction_Call) Return(_a0 error) *TxManager_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxManager_WithTransaction_Call) RunAndReturn(run func(context.Context, func(repository.OrderRepository) error) error) *TxManager_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxManager creates a new instance of TxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxManager {
	mock := &TxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
